-- Advanced:
-- Calculate the percentage contribution of each pizza type to total revenue.
-- select pt.category, round(sum(od.quanity*p.price)/(select round(sum(od.quanity*p.price), 2) as Total_revenues 
-- from order_details od
-- join pizzas p
-- on od.pizza_id = p.pizza_id)*100,2) as revenue
-- from pizza_types pt
-- order by revenue desc

-- Analyze the cumulative revenue generated over time.
-- join pizzas p
-- on pt.pizza_type_id = p.pizza_type_id
-- join order_details od
-- on od.pizza_id = p.pizza_id
-- group by pt.category
-- select order_date, sum(revenue) over(order by order_date) as cum_reve
-- from 
-- (SELECT SUM(od.quanity * p.price) AS revenue, date(o.order_date)
-- FROM orders o
-- JOIN order_details od ON o.order_id = od.order_id
-- JOIN pizzas p ON od.pizza_id = p.pizza_id
-- GROUP BY date(o.order_date)
-- order by date(o.order_date) ) as sales

-- Determine the top 3 most ordered pizza types based on revenue for each pizza category.

-- with cte as (select pt.name as pizza_type, pt.category, sum(od.quanity*p.price) as revenue, row_number() over(partition by pt.category order by sum(od.quanity*p.price) DESC) as rn
-- from order_details od
-- join pizzas p
-- on od.pizza_id = p.pizza_id
-- join pizza_types pt
-- on p.pizza_type_id = pt.pizza_type_id
-- group by pt.name, pt.category )
-- select pizza_type, category, revenue
-- from cte
-- where rn<=3